### ISSUE TITLE
ED will not acknowledge any commands

### ISSUE THREAD

**Issue by CMDRSlyraccoon** [mhwlng/streamdeck-elite#5]
Thanks for designing a awesome plugin but Elite will not acknowledge any commands given the Log is below

2020-04-21 16:45:22.1787|DEBUG|BarRaider.SdTools.Logger|Logger Initialized
2020-04-21 16:45:22.2118|INFO|BarRaider.SdTools.Logger|Init Elite Api
2020-04-21 16:45:22.2118|INFO|BarRaider.SdTools.Logger|journal path C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous
2020-04-21 16:45:22.8379|FATAL|BarRaider.SdTools.Logger|Elite Api: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Dion\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\StartPreset.start'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Elite.Program.Main(String[] args)
2020-04-21 16:45:22.8469|INFO|BarRaider.SdTools.Logger|Plugin Loading - 3 Actions Found
2020-04-21 16:45:23.0069|INFO|BarRaider.SdTools.Logger|Plugin version: 1.6.0
2020-04-21 16:45:23.0069|INFO|BarRaider.SdTools.Logger|Connecting to Stream Deck
2020-04-21 16:45:25.0544|INFO|BarRaider.SdTools.Logger|Connected to Stream Deck
2020-04-21 16:45:25.0544|INFO|BarRaider.SdTools.Logger|GlobalSettingsManager initialized
2020-04-21 20:11:17.2761|INFO|BarRaider.SdTools.Logger|Disconnect event received
2020-04-21 20:11:17.2761|INFO|BarRaider.SdTools.Logger|Plugin Disconnected - Exiting

Thanks

CMDR
[log.000.log](https://github.com/mhwlng/streamdeck-elite/files/4532328/log.000.log)

**Comment by mhwlng** [comment]
According to your log, the problem is that it can't find this file :

`C:\Users\Dion\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\StartPreset.start
`

I need to know where this file exists on your PC ?

**Comment by CMDRSlyraccoon** [comment]
I do not know why it would not work though the game has been installed
since 2015 would it work just renaming one of the bindings to that?

**Comment by mhwlng** [comment]
no, StartPreset.start is created every time you change the controls in ED.
StartPreset.start does not contain the bindings themselves. it contains part of the bindings file name.

 I need to know where this file exists on your PC ?

**Comment by CMDRSlyraccoon** [comment]
I will have another look when I get home thanks for your help so far

**Comment by CMDRSlyraccoon** [comment]
That file is there I deleted it and booted the game so it shows back up
[image: image.png]

**Comment by mhwlng** [comment]
I can't see your image.png ?
Is this the exact spelling of the directory (including capitalization) :
C:\Users\Dion\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\StartPreset.start

maybe the problem is that the plugin has no access rights to this directory, for some reason ?

**Comment by CMDRSlyraccoon** [comment]
could my virus protection be blocking it perhaps? Image.png?

**Comment by mhwlng** [comment]
I don't know. I also I can't see any images in your posts here.

**Comment by mhwlng** [comment]
can you confirm 
Is this the exact spelling of the directory (including capitalization) :
C:\Users\Dion\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\StartPreset.start

**Comment by CMDRSlyraccoon** [comment]
Yes it is

**Comment by mhwlng** [comment]
are you logged in as user Dion?

**Comment by CMDRSlyraccoon** [comment]
yes it is not just a local account though. the stream deck can see the pips
settings

**Comment by mhwlng** [comment]
the pips settings come from another directory
C:\Users\Dion\Saved Games\Frontier Developments\Elite Dangerous

**Comment by mhwlng** [comment]
I have not found a reason why this code would fail on your pc, if the file and path exists:
```
var path = $@"C:\Users\{Environment.UserName}\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\";
var bindsName = File.ReadAllText(path + "StartPreset.start");

```

The only thing that I can think of is a problem with access rights.
So that the streamdeck software is not allowed to look into the directory or open that file ?

**Comment by CMDRSlyraccoon** [comment]
I think my virus protection may being overzealous

**Comment by mhwlng** [comment]
I don't know, that's not something I can verify...

**Comment by mhwlng** [comment]
can you open StartPreset.start in notepad ? does it contain the file name of the selected binds file

**Comment by CMDRSlyraccoon** [comment]
I have tried reinstalling the plugin. and streamdeck running in admin mode

**Comment by mhwlng** [comment]
can you open StartPreset.start in notepad ? does it contain the file name of the selected binds file

**Comment by CMDRSlyraccoon** [comment]
Yes Custom as my current preset is custom

**Comment by mhwlng** [comment]
I'm afraid I don't know what the problem is and why this fails on your pc....

```
var path = $@"C:\Users\{Environment.UserName}\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\";
var bindsName = File.ReadAllText(path + "StartPreset.start");
```

**Comment by CMDRSlyraccoon** [comment]
Ah well I will keep looking and keep you posted.

**Comment by mhwlng** [comment]
please try 1.7.0 to see if that makes any difference?
I added some more more logging. So If it doesn't work please check the log

**Comment by CMDRSlyraccoon** [comment]
I will have a go thank you very much

**Comment by CMDRSlyraccoon** [comment]
Its working now. aside from some incorrect key presses probably due to my
custom mapping

**Comment by mhwlng** [comment]
Ok, then the directory must now be different from 'C:\Users\Dion\AppData\Local' ?
is it on a different drive letter, perhaps ?
The log should show the actual bindings directory being used.

I don't know about incorrect key mappings ?
You can check the custom.binds file, to see what keypresses the plugin uses for a specific function
(If you only have a binding for a joystick/controller then it won't work)

**Comment by CMDRSlyraccoon** [comment]
Do you want my current log so you can check it?

**Comment by mhwlng** [comment]
sure

**Comment by CMDRSlyraccoon** [comment]
2020-04-25 19:17:09.3991|DEBUG|BarRaider.SdTools.Logger|Logger Initialized
2020-04-25 19:17:09.4251|INFO|BarRaider.SdTools.Logger|Init Elite Api
2020-04-25 19:17:09.4251|INFO|BarRaider.SdTools.Logger|journal path
C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous
2020-04-25 19:17:09.8712|INFO|BarRaider.SdTools.Logger|bindings path
C:\Users\User\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Bindings
2020-04-25 19:17:09.9272|INFO|BarRaider.SdTools.Logger|using
C:\Users\User\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Bindings\Custom.3.0.binds
2020-04-25 19:17:09.9802|INFO|BarRaider.SdTools.Logger|Plugin Loading - 3
Actions Found
2020-04-25 19:17:10.1032|INFO|BarRaider.SdTools.Logger|Plugin version: 1.7.0
2020-04-25 19:17:10.1032|INFO|BarRaider.SdTools.Logger|Connecting to Stream
Deck
2020-04-25 19:17:12.1402|INFO|BarRaider.SdTools.Logger|Connected to Stream
Deck
2020-04-25
19:17:12.1422|INFO|BarRaider.SdTools.Logger|GlobalSettingsManager
initialized
2020-04-25 19:19:55.0639|FATAL|BarRaider.SdTools.Logger|Unhandled
Exception: System.InvalidOperationException: Object is currently in use
elsewhere.
   at System.Drawing.Image.get_Width()
   at System.Drawing.Bitmap..ctor(Image original)
   at Elite.Power.<HandleDisplay>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at Elite.Power.<<-ctor>b__9_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at
System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object
state)
   at
System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object
state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
2020-04-25 19:19:58.7207|FATAL|BarRaider.SdTools.Logger|Unhandled
Exception: System.InvalidOperationException: Object is currently in use
elsewhere.
   at System.Drawing.Image.get_Width()
   at System.Drawing.Bitmap..ctor(Image original)
   at Elite.Power.<HandleDisplay>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at Elite.Power.<<-ctor>b__9_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at
System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object
state)
   at
System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object
state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
2020-04-25 19:19:59.1327|DEBUG|BarRaider.SdTools.Logger|Logger Initialized
2020-04-25 19:19:59.1697|INFO|BarRaider.SdTools.Logger|Init Elite Api
2020-04-25 19:19:59.1697|INFO|BarRaider.SdTools.Logger|journal path
C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous
2020-04-25 19:19:59.6800|INFO|BarRaider.SdTools.Logger|bindings path
C:\Users\User\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Bindings
2020-04-25 19:19:59.7390|INFO|BarRaider.SdTools.Logger|using
C:\Users\User\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Bindings\Custom.3.0.binds
2020-04-25 19:19:59.8050|INFO|BarRaider.SdTools.Logger|Plugin Loading - 3
Actions Found
2020-04-25 19:19:59.9480|INFO|BarRaider.SdTools.Logger|Plugin version: 1.7.0
2020-04-25 19:19:59.9480|INFO|BarRaider.SdTools.Logger|Connecting to Stream
Deck
2020-04-25 19:20:01.9885|INFO|BarRaider.SdTools.Logger|Connected to Stream
Deck
2020-04-25
19:20:01.9885|INFO|BarRaider.SdTools.Logger|GlobalSettingsManager
initialized
2020-04-25 19:25:25.0559|INFO|BarRaider.SdTools.Logger|Disconnect event
received
2020-04-25 19:25:25.0559|INFO|BarRaider.SdTools.Logger|Plugin Disconnected
- Exiting
2020-04-25 19:25:33.0539|DEBUG|BarRaider.SdTools.Logger|Logger Initialized
2020-04-25 19:25:33.0859|INFO|BarRaider.SdTools.Logger|Init Elite Api
2020-04-25 19:25:33.0859|INFO|BarRaider.SdTools.Logger|journal path
C:\Users\User\Saved Games\Frontier Developments\Elite Dangerous
2020-04-25 19:25:33.5881|INFO|BarRaider.SdTools.Logger|bindings path
C:\Users\User\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Bindings
2020-04-25 19:25:33.6461|INFO|BarRaider.SdTools.Logger|using
C:\Users\User\AppData\Local\Frontier Developments\Elite
Dangerous\Options\Bindings\Custom.3.0.binds
2020-04-25 19:25:33.7041|INFO|BarRaider.SdTools.Logger|Plugin Loading - 3
Actions Found
2020-04-25 19:25:33.8431|INFO|BarRaider.SdTools.Logger|Plugin version: 1.7.0
2020-04-25 19:25:33.8431|INFO|BarRaider.SdTools.Logger|Connecting to Stream
Deck
2020-04-25 19:25:35.8846|INFO|BarRaider.SdTools.Logger|Connected to Stream
Deck
2020-04-25
19:25:35.8846|INFO|BarRaider.SdTools.Logger|GlobalSettingsManager
initialized

**Comment by mhwlng** [comment]
So, for some reason, the correct directory is C:\Users\User\AppData\ and not C:\Users\Dion\AppData\

**Comment by CMDRSlyraccoon** [comment]
Not a clue why it wants to misbehave? oh well it is fixed thanks for
all your help!!!!!

Your app is Awesome everyone needs it

Thanks Again

CMDR

**Comment by mhwlng** [comment]
Ok no problem,

> aside from some incorrect key presses probably due to my custom mapping

If, after looking at the binds file yourself, you still think that this may be a problem in the plugin, 
open another issue and then attach the active binds file with more information about which key is having problems.
