### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by fatlazycat** [mhwlng/streamdeck-elite#62]
Was all working then ( i think ) during a relog the stream deck controls just stopped working with the plugin. Other stream deck controls are fine.

I tried to reinstall the plugin but no difference, reboot of the PC doesn't fix it.

Log has the following 

Thanks

```
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.7354|DEBUG|com.mhwlng.elite|1|Logger Initialized
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.7590|INFO|com.mhwlng.elite|1|Init Elite Api
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.7590|INFO|com.mhwlng.elite|1|LocalApplicationData path C:\Users\graha\AppData\Local
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.7590|INFO|com.mhwlng.elite|1|Directory found C:\Users\graha\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.7590|INFO|com.mhwlng.elite|1|StartPreset.4.start found C:\Users\graha\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\StartPreset.4.start
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|INFO|com.mhwlng.elite|1|startpreset contents : Gladiator NXT
Gladiator NXT
Gladiator NXT
Gladiator NXT
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|INFO|com.mhwlng.elite|1|key bindings Gladiator NXT
,Gladiator NXT
,Gladiator NXT
,Gladiator NXT
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|INFO|com.mhwlng.elite|1|monitoring key binding path #1 C:\Users\graha\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|INFO|com.mhwlng.elite|1|monitoring key binding file name #1 StartPreset.4.start
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|INFO|com.mhwlng.elite|1|odyssey key bindings
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|INFO|com.mhwlng.elite|1|handle key binding Gladiator NXT

[2024-02-10](canary:event?ts=729259205.00) 15:53:13.8653|FATAL|com.mhwlng.elite|1|Elite Api: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at Elite.Program.HandleKeyBinding(BindingType bindingType, String bindingsPath, String bindsName)
   at Elite.Program.GetKeyBindings(Object threadContext)
   at Elite.Program.Main(String[] args)
[2024-02-10](canary:event?ts=729259205.00) 15:53:13.9653|INFO|com.mhwlng.elite|1|Plugin [com.mhwlng.elite] Loading - 12 Actions Found
[2024-02-10](canary:event?ts=729259205.00) 15:53:14.0790|DEBUG|com.mhwlng.elite|1|Plugin Loaded: UUID: 10373506EEB59CFD1F6BB24E23E7C36C Device Info: Devices:
[Id: D6B9E5F7DE0528C8DAD7448D2BD20E78 Type: StreamDeckXL Size: Rows: 4 Columns: 8]
ApplicationInfo: Language: en Platform: windows Version: 6.5.0.19904
PluginInfo: Version: 2.6.0

[2024-02-10](canary:event?ts=729259205.00) 15:53:14.0790|INFO|com.mhwlng.elite|1|Plugin version: 2.6.0
[2024-02-10](canary:event?ts=729259205.00) 15:53:14.0790|INFO|com.mhwlng.elite|1|Connecting to Stream Deck...
[2024-02-10](canary:event?ts=729259205.00) 15:53:16.1416|INFO|com.mhwlng.elite|1|Connected to Stream Deck
[2024-02-10](canary:event?ts=729259205.00) 15:53:16.1416|INFO|com.mhwlng.elite|1|GlobalSettingsManager initialized
[2024-02-10](canary:event?ts=729259205.00) 15:53:16.1988|FATAL|com.mhwlng.elite|5|Could not create instance of Elite.Buttons.Hyperspace with context 4225c03447bd50ff8543b12b129d70e0 - This may be due to an Exception raised in the constructor, or the class does not inherit PluginBase with the same constructor System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elite.Buttons.Hyperspace..ctor(SDConnection connection, InitialPayload payload)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at BarRaider.SdTools.PluginContainer.<Connection_OnWillAppear>d__14.MoveNext()
[2024-02-10](canary:event?ts=729259205.00) 15:53:16.2184|FATAL|com.mhwlng.elite|5|Could not create instance of Elite.Buttons.Hyperspace with context d050d19bbef7bc57a318f9747bdc822e - This may be due to an Exception raised in the constructor, or the class does not inherit PluginBase with the same constructor System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elite.Buttons.Hyperspace..ctor(SDConnection connection, InitialPayload payload)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at BarRaider.SdTools.PluginContainer.<Connection_OnWillAppear>d__14.MoveNext()
[2024-02-10](canary:event?ts=729259205.00) 15:53:16.2289|FATAL|com.mhwlng.elite|5|Could not create instance of Elite.Buttons.Toggle with context da01a3bb41f1af2436165ef364fd73bf - This may be due to an Exception raised in the constructor, or the class does not inherit PluginBase with the same constructor System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elite.Buttons.Toggle..ctor(SDConnection connection, InitialPayload payload)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at BarRaider.SdTools.PluginContainer.<Connection_OnWillAppear>d__14.MoveNext()
[2024-02-10](canary:event?ts=729259205.00) 15:53:16.2289|FATAL|com.mhwlng.elite|5|Could not create instance of Elite.Buttons.Toggle with context cd5d4cebab6fad22c6cac40a02fc3f8e - This may be due to an Exception raised in the constructor, or the class does not inherit PluginBase with the same constructor System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Elite.Buttons.Toggle..ctor(SDConnection connection, InitialPayload payload)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at BarRaider.SdTools.PluginContainer.<Connection_OnWillAppear>d__14.MoveNext()
```

**Comment by mhwlng** [comment]
The error is Illegal characters in path. 
I see that your binding is Gladiator nxt. This is not right. All 4 bindings should be 'custom' as described on GitHub.

**Comment by fatlazycat** [comment]
Thanks, not sure how it was working before but all good when renamed !

Thanks again for the plugin !
